namespace WynncraftSharp.Items;

public class Item
{
    public string Name { get; internal set; }
    public string Tier { get; internal set; }
    public string Set { get; internal set; }
    public ushort Sockets { get; internal set; }
    public string Type { get; internal set; }
    public string ArmorType { get; internal set; }
    public string ArmorColor { get; internal set; }
    public string AddedLore { get; internal set; }
    public string Material { get; internal set; }
    public string DropType { get; internal set; }
    public string Restrictions { get; internal set; }
    public string Damage { get; internal set; }
    public string FireDamage { get; internal set; }
    public string WaterDamage { get; internal set; }
    public string AirDamage { get; internal set; }
    public string ThunderDamage { get; internal set; }
    public string EarthDamage { get; internal set; }
    public string AttackSpeed { get; internal set; }
    public uint Health { get; internal set; }
    public ushort FireDefense { get; internal set; }
    public ushort WaterDefense { get; internal set; }
    public ushort AirDefense { get; internal set; }
    public ushort ThunderDefense { get; internal set; }
    public ushort EarthDefense { get; internal set; }
    public ushort Level { get; internal set; }
    public string Quest { get; internal set; }
    public string ClassRequirement { get; internal set; }
    public ushort Strength { get; internal set; }
    public ushort Dexterity { get; internal set; }
    public ushort Intelligence { get; internal set; }
    public ushort Ability { get; internal set; }
    public ushort Defense { get; internal set; }
    public ushort HealthRegen { get; internal set; }
    public ushort ManaRegen { get; internal set; }
    public ushort SpellDamage { get; internal set; }
    public ushort DamageBonus { get; internal set; }
    public ushort LifeSteal { get; internal set; }
    public ushort ManaSteal { get; internal set; }
    public ushort XpBonus { get; internal set; }
    public ushort LootBonus { get; internal set; }
    public ushort Reflection { get; internal set; }
    public ushort StrengthPoints { get; internal set; }
    public ushort DexterityPoints { get; internal set; }
    public ushort IntelligencePoints { get; internal set; }
    public ushort AbilityPoints { get; internal set; }
    public ushort DefensePoints { get; internal set; }
    public ushort Thorns { get; internal set; }
    public ushort Exploding { get; internal set; }
    public ushort Speed { get; internal set; }
    public ushort AttackSpeedBonus { get; internal set; }
    public ushort Poison { get; internal set; }
    public ushort HealthBonus { get; internal set; }
    public ushort SoulPoints { get; internal set; }
    public ushort EmeraldStealing { get; internal set; }
    public uint HealthRegenRaw { get; internal set; }
    public uint SpellDamageRaw { get; internal set; }
    public uint DamageBonusRaw { get; internal set; }
    public ushort BonusFireDamage { get; internal set; }
    public ushort BonusWaterDamage { get; internal set; }
    public ushort BonusAirDamage { get; internal set; }
    public ushort BonusThunderDamage { get; internal set; }
    public ushort BonusEarthDamage { get; internal set; }
    public ushort BonusFireDefense { get; internal set; }
    public ushort BonusWaterDefense { get; internal set; }
    public ushort BonusAirDefense { get; internal set; }
    public ushort BonusThunderDefense { get; internal set; }
    public ushort BonusEarthDefense { get; internal set; }
    public string AccessoryType { get; internal set; }
    public bool Identified { get; internal set; }
    public string Skin { get; internal set; }
    public string Category { get; internal set; }
}